# Vectorization 

* Vectorization is the process of performing operations on an entire array at once instead of using loops( for or while).

* It makes NumPy programs:
    1. Faster
    2. Simpler
    3. More memory efficient

In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])

1. Addition of two number.

In [4]:
print(arr1+arr2)

[11 22 33]


2. Multiplication

In [5]:
print(arr1*2) 
# Here broadcasting is also used.

[2 4 6]


3. np.sqrt(array)

In [6]:
print(np.sqrt(np.array([1,4,9,16,36,49])))

[1. 2. 3. 4. 6. 7.]
